---
title: "R Notebook"
output: html_notebook
---
```{r warning=FALSE}
# if using mac:
setwd("~/Dropbox/MOOK")
# if using win:
#setwd("C:/Users/Chen/Dropbox/MOOK")
#load data
dat <- read.csv("CS50_ChosenUsers_1_irt.csv",header=TRUE, sep=",")
```
```{r warning=FALSE}
#those folllow the sequence are regular students, and those do not follow the seqence are irregular students
#please note this does not count p9, the final.
dat$regular<-NA
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==0 & dat$p0==1 )] <- 1
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2==0 & dat$p1==1 & dat$p0==1 )] <- 2
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3==0 & dat$p2+ dat$p1==2 & dat$p0==1 )] <- 3
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4==0 & dat$p3+ dat$p2+ dat$p1==3 & dat$p0==1 )] <- 4
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5==0 & dat$p4+ dat$p3+ dat$p2+ dat$p1==4 & dat$p0==1 )] <- 5
dat$regular[which(dat$p8 + dat$p7 + dat$p6==0 & dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==5 & dat$p0==1 )] <- 6
dat$regular[which(dat$p8 + dat$p7 ==0 & dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==6 & dat$p0==1 )] <- 7
dat$regular[which(dat$p8 == 0 & dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==7 & dat$p0==1 )] <- 8
dat$regular[which(dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==8 & dat$p0==1 )] <- 9


dat$regularf<-NA
#dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1> 0 & dat$p0 ==1 )] <- 0
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==0 & dat$p0==1 )] <- 1
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2==0 & dat$p1==1 & dat$p0==1 )] <- 2
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3==0 & dat$p2+ dat$p1==2 & dat$p0==1 )] <- 3
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4==0 & dat$p3+ dat$p2+ dat$p1==3 & dat$p0==1 )] <- 4
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5==0 & dat$p4+ dat$p3+ dat$p2+ dat$p1==4 & dat$p0==1 )] <- 5
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6==0 & dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==5 & dat$p0==1 )] <- 6
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 ==0 & dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==6 & dat$p0==1 )] <- 7
dat$regularf[which(dat$p9 + dat$p8 == 0 & dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==7 & dat$p0==1 )] <- 8
dat$regularf[which(dat$p9 == 0 & dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==8 & dat$p0==1 )] <- 9
dat$regularf[which(dat$p9 + dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1==9 & dat$p0==1 )] <- 10

dat$irregular <- NA
dat$irregular[which(is.na(dat$regularf) & dat$p0==1)] <- 1
dat$irregular[which(dat$regularf > 0 & dat$p0==1)] <- 0
```
```{r warning=FALSE}
#processing some other variables
#set reference date to 2014 May, created binary enroll phase.
#add number of computer language, number of none-zero, highest profeciency in any language
dat$age = 2015- as.numeric(as.character(dat$profile_year_of_birth))
dat$age[which(dat$age<10)] <- NA
dat$age[which(dat$age>80)] <- NA
dat$age[which(dat$age>69)] <- NA
#dat$c0 <- as.numeric(as.character(dat$c0))
dat$c1 <- as.numeric(as.character(dat$c1))
dat$c2 <- as.numeric(as.character(dat$c2))
dat$c3 <- as.numeric(as.character(dat$c3))
dat$c4 <- as.numeric(as.character(dat$c4))
dat$c5 <- as.numeric(as.character(dat$c5))
dat$c6 <- as.numeric(as.character(dat$c6))
dat$c7 <- as.numeric(as.character(dat$c7))
dat$c8 <- as.numeric(as.character(dat$c8))
dat$c9 <- as.numeric(as.character(dat$c9))
dat$c10 <- as.numeric(as.character(dat$c10))

dat$edu <- 7-as.numeric(as.character(dat$profile_level_of_education))
dat$enrollday<- as.Date(dat$enrollment_created, "%Y-%m-%d %H:%M")
dat$refday<- as.Date(dat$couse_all_upload, "%Y-%m-%d %H:%M")
dat$enrolltime <- as.numeric(dat$enrollday - dat$refday)
dat$numlang <- as.numeric(as.character(dat$num_lang))
dat$edu[which(dat$edu<1)] <- NA
dat$father_ed[which(dat$father_ed>6)]<-NA
dat$father_edu <- 6-dat$father_ed
dat$mother_ed[which(dat$mother_ed>6)]<-NA
dat$mother_edu <- 6-dat$mother_ed
dat$engfluent <- dat$fluent_1 + dat$fluent_2 + dat$fluent_3 + dat$fluent_4
dat$nointendcomplete <- dat$complete_1 + dat$complete_2 + dat$complete_3 
dat$sat_math[which(dat$sat_math<300)] <- NA
dat$sat_verb[which(dat$sat_verb<200)] <-NA
dat$prog_year <- as.numeric(as.character(dat$prog_years))
dat$exp <- NA
dat$exp[which(dat$experience==1)] <- 1
dat$exp[which(dat$experience==0)] <- 0
dat$reason_lc <- as.factor(dat$reason_lc)
dat$reason_lc[which(dat$reason_lc==3)] <- NA
dat$reason <- as.numeric(dat$reason_lc)
dat$foreign[which(is.na(dat$COUNTRY))] <- NA
dat$npset <- NA
dat$npset <-  dat$p8 + dat$p7 + dat$p6+dat$p5+ dat$p4+ dat$p3+ dat$p2+ dat$p1
dat$reason_lc[which(dat$reason_lc==0)] <-1
dat$extrovert <- as.numeric(as.character(dat$introvert))
dat$extrovert[which(dat$extrovert == 4)] <-3
dat$extrovert[which(dat$extrovert == 5)] <- 4
dat$colab_pref<- as.numeric(dat$colab_pref)
dat$progroup <- NA
dat$progroup[which(dat$colab_pref==4)] <-2
dat$progroup[which(dat$colab_pref==6)] <- 0
dat$progroup[which(dat$colab_pref==3 | dat$colab_pref==5)] <- 1
#dat$cert <- 4- dat$cert
dat$nohelp <- dat$ppl_help_11
dat$gamehour5 <- as.numeric(as.character(dat$games))
dat$maxproglang <- apply(dat[187:223], 1, function(x) max(x, na.rm=TRUE))
dat$maxproglang[which(dat$maxproglang<0)] <- 0
dat$totalproglang <- apply(dat[301:332], 1, function(x) sum(x, na.rm=TRUE))
dat$totalproglang[which(dat$totalproglang>21)] <- 21

dat$forums <- 3-dat$forums
dat$exp_complete_video <- dat$complete_1
dat$exp_complete_assign <- dat$complete_2
dat$exp_complete_final <- dat$complete_3
#need to remove NAs when calculating the max
```

```{r warning=FALSE}
#only interested in row that have pretest information (p0==1)
dat2 = dat[dat$p0==1,]
```
```{r warning=FALSE}
#total number of milestones completed, regardless of order.
 dat2$m1 <- 0
 dat2$m2 <- NA
 dat2$m3 <- NA
 dat2$m4 <- NA
 dat2$m5 <- NA
 dat2$m6 <- NA
 dat2$m7 <- NA
 dat2$m8 <- NA
 dat2$m9 <- NA
 dat2$m10 <- NA
dat2$m1[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9 + dat2$p0>0 )] <- 1
dat2$m2[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>1 )] <- 1
dat2$m3[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>2 )] <- 1
dat2$m4[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>3 )] <- 1
dat2$m5[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>4 )] <- 1
dat2$m6[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>5 )] <- 1
dat2$m7[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>6 )] <- 1
dat2$m8[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>7 )] <- 1
dat2$m9[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>8 )] <- 1
dat2$m10[which(dat2$p8 + dat2$p7 + dat2$p6+dat2$p5+ dat2$p4+ dat2$p3+ dat2$p2+ dat2$p1 + dat2$p9+ dat2$p0>9 )] <- 1
dat2$ms <- rowSums(cbind(dat2$m1 ,dat2$m2 ,dat2$m3 ,dat2$m4,dat2$m5,dat2$m6,dat2$m7,dat2$m8,dat2$m9,dat2$m10), na.rm=TRUE)
table(dat2$ms)
```
```{r}
dat2$m1[which(dat2$ms==0)] <- 0

dat2$m2[which(dat2$ms==1)] <- 0
dat2$m3[which(dat2$ms==2)] <- 0
dat2$m4[which(dat2$ms==3)] <- 0
dat2$m5[which(dat2$ms==4)] <- 0
dat2$m6[which(dat2$ms==5)] <- 0
dat2$m7[which(dat2$ms==6)] <- 0
dat2$m8[which(dat2$ms==7)] <- 0
dat2$m9[which(dat2$ms==8)] <- 0
dat2$m10[which(dat2$ms==9)] <- 0
table(dat2$m10)
table(dat2$m1)
```
```{r}

dat2$d1 <- 1-dat2$m1
dat2$d2 <- 1-dat2$m2
dat2$d3 <- 1-dat2$m3
dat2$d4 <- 1-dat2$m4
dat2$d5 <- 1-dat2$m5
dat2$d6 <- 1-dat2$m6
dat2$d7 <- 1-dat2$m7
dat2$d8 <- 1-dat2$m8
dat2$d9 <- 1-dat2$m9
dat2$d10 <- 1-dat2$m10

dat2$event <- 1
dat2$event[which(dat2$ms==10)] <- 0

dat2$censor = 1-dat2$event

table(dat2$event)
table(dat2$censor)
```


```{r warning=FALSE}
library(MASS)
dat2$age <- scale(dat2$age,center = TRUE, scale = TRUE)
dat2$cert <- scale(dat2$cert,center = TRUE, scale = TRUE)
dat2$oc_reg <- scale(dat2$oc_reg,center = TRUE, scale = TRUE)
dat2$oc_comp <- scale(dat2$oc_comp,center = TRUE, scale = TRUE)
dat2$fam <- scale(dat2$fam,center = TRUE, scale = TRUE)
dat2$nointendcomplete <- scale(dat2$nointendcomplete,center = TRUE, scale = TRUE)
dat2$engfluent <- scale(dat2$engfluent,center = TRUE, scale = TRUE)
dat2$numlang <- scale(dat2$numlang,center = TRUE, scale = TRUE)
dat2$testtot <- scale(dat2$testtot,center = TRUE, scale = TRUE)
dat2$enrolltime <- scale(dat2$enrolltime,center = TRUE, scale = TRUE)
#dat2$exp <- scale(dat2$exp,center = TRUE, scale = TRUE)
dat2$extrovert <- scale(dat2$extrovert,center = TRUE, scale = TRUE)
dat2$gamehour5 <- scale(dat2$gamehour5,center = TRUE, scale = TRUE)
dat2$maxproglang <- scale(dat2$maxproglang,center = TRUE, scale = TRUE)
dat2$totalproglang <- scale(dat2$totalproglang,center = TRUE, scale = TRUE)
dat2$prog_year <- scale(dat2$prog_year,center = TRUE, scale = TRUE)
dat2$reason <- scale(dat2$reason,center = TRUE, scale = TRUE)
dat2$forums <- scale(dat2$forums,center = TRUE, scale = TRUE)
dat2$exp_complete_assign <- scale(dat2$exp_complete_assign,center = TRUE, scale = TRUE)
dat2$exp_complete_video <- scale(dat2$exp_complete_video,center = TRUE, scale = TRUE)
dat2$exp_complete_final <- scale(dat2$exp_complete_final,center = TRUE, scale = TRUE)
dat2$age <- as.numeric(dat2$age)
dat2$cert <- as.numeric(dat2$cert)
dat2$oc_reg <- as.numeric(dat2$oc_reg)
dat2$oc_comp <- as.numeric(dat2$oc_comp)
dat2$fam <- as.numeric(dat2$fam)
dat2$nointendcomplete <- as.numeric(dat2$nointendcomplete)
dat2$engfluent <- as.numeric(dat2$engfluent)
dat2$numlang <- as.numeric(dat2$numlang)
dat2$testtot <- as.numeric(dat2$testtot)
dat2$enrolltime <- as.numeric(dat2$enrolltime)
#dat2$exp <- as.numeric(dat2$exp)
dat2$extrovert <- as.numeric(dat2$extrovert)
dat2$gamehour5 <- as.numeric(dat2$gamehour5)
dat2$maxproglang <- as.numeric(dat2$maxproglang)
dat2$totalproglang <- as.numeric(dat2$totalproglang)
dat2$prog_year <- as.numeric(dat2$prog_year)
dat2$reason <- as.numeric(dat2$reason)
dat2$forums <- as.numeric(dat2$forums)
dat2$exp_complete_assign <- as.numeric(dat2$exp_complete_assign)
dat2$exp_complete_video <- as.numeric(dat2$exp_complete_video)
dat2$exp_complete_final <- as.numeric(dat2$exp_complete_final)
dat2$prog_year <- as.numeric(dat2$prog_year)
dat2$forumexp <- scale(dat2$forum_exp,center = TRUE, scale = TRUE)
dat2$forumexp <- as.numeric(dat2$forum_exp)
```

```{r warning=FALSE}
library(psych)
library(GPArotation)
factorvar <- with(dat2, data.frame(cert,reason, oc_reg , oc_comp , fam , engfluent, numlang , school ,testtot ,foreign, prog_year, extrovert,  nohelp, gamehour5,maxproglang,totalproglang, forums, exp_complete_final,exp_complete_video, exp_complete_assign, testtot))
corMat <- cor(factorvar, use = "pairwise.complete.obs")
solution<-fa(r=corMat, nfactors = 4,rotate = "oblimin",fm="pa")
solution
```
```{r warning=FALSE}
dat2$motiv <- (dat2$cert+ dat2$exp_complete_assign+dat2$exp_complete_final+dat2$exp_complete_video+dat2$forums)/5

dat2$numcourse <- (dat2$oc_comp+dat2$oc_reg)/2
dat2$csexperience <- (dat2$prog_year+dat2$fam+dat2$maxproglang+dat2$totalproglang)/4

dat2$motiv <- scale(dat2$motiv,center = TRUE, scale = TRUE)
dat2$csexperience <- scale(dat2$csexperience, center = TRUE, scale = TRUE)
dat2$numcourse <- scale(dat2$numcourse,center = TRUE, scale = TRUE)
```

```{r results='asis', warning=FALSE}
dat3<-dat2[dat2$irregular==0,]
table(dat3$censor)
table(dat3$d10)
```

```{r results='asis', warning=FALSE}
library(rms)
 library(KMsurv)
 library(nlme)
 library(survminer)
 library(survMisc)
library(multcomp)
library(reshape2)
```
```{r}
dat4 <- reshape(dat3, dir="long",varying = list(375:384,435:444), timevar = "milestone",v.names = c('click','drop'),idvar="user_id")
```
```{r}
dat5 <- dat4[order(dat4$user_id),]
dat5[1:20,428:433]
```

```{r}
dat6 <- dat5[complete.cases(dat5$drop),]
dat6[1:20,428:433]
```

```{r results="asis", warning=FALSE, message=FALSE}
dat7 <- dat6[, c("user_id","ms","censor","age", "edu", "male", "enrollment_mode", "reason", "cert","oc_reg" , "oc_comp" , "fam" , "engfluent" , "nointendcomplete" , "school" ,  "numlang" , "testtot" ,"enrolltime" ,"foreign", "extrovert", "nohelp", "gamehour5","maxproglang","totalproglang","prog_year","motiv","csexperience","numcourse","milestone","click","drop","event")]

```

```{r}
dat7$motivhigh <- NA
dat7$motivhigh[which(dat7$motiv < 0.35)] <- 0
dat7$motivhigh[which(dat7$motiv > 0.35)] <- 1
table(dat7$motivhigh)

dat7$testhigh <- NA
dat7$testhigh[which(dat7$testtot < -1.4 & dat7$testtot > -2)] <- 0
dat7$testhigh[which(dat7$testtot < 0 & dat7$testtot > -0.03)] <- 1
table(dat7$testhigh)

dat7$testabovemedian <- NA
dat7$testabovemedian[which(dat7$testtot < 0)] <- 0
dat7$testabovemedian[which(dat7$testtot > 0)] <- 1
table(dat7$testabovemedian)

dat7$milestone2 <- dat7$milestone^2
dat7$milestone3 <- dat7$milestone^3

dat9 <- dat7
dat9$milestones = dat9$milestone-1
dat9<- dat9[dat9$milestones>0,]
```
```{r}
dat9$milestone2 <- dat9$milestone^2
dat9$milestone3 <- dat9$milestone^3
dat9$mss <- dat9$ms+1
```
```{r}
save(dat7, file = "CS50_MOOC_Survival_Analysis_Data_0.RData")

save(dat9, file = "CS50_MOOC_Survival_Analysis_Data_1.RData")
```

```{r}
timevaryingmodel <- glm(drop ~ milestone + milestone2 + milestone3+ male +milestone*male +  age +  testtot  +foreign + gamehour5 + testtot*milestone  , family="binomial", data=dat8)
summary(timevaryingmodel)
```
```{r}
 datK <- dat7[complete.cases(dat7),]

newdat <- data.frame(milestone=datK$milestone, milestone2=datK$milestone2,milestone3 = datK$milestone3, male = datK$male, age = datK$age,  testtot = datK$testtot, foreign = datK$foreign, extrovert = datK$extrovert, gamehour5 = datK$gamehour5, csexperience = datK$csexperience, motiv = datK$motiv)
datK$predict_value <- predict(timevaryingmodel2, newdat, type='link')
fitline <- predict(timevaryingmodel2, newdat, type='link',se.fit = TRUE)
datK$predict_probability <- predict(timevaryingmodel2, newdat, type='response')
datK$sefit <- fitline$se.fit
datK$predict_term <- predict(timevaryingmodel2, newdat, type='term')

```
```{r}
datL <- datK[datK$milestone < 9,]
```
```{r}
datL$model <- "L"
datK$model <- "C"
datC <- rbind(datL, datK)
```
mean log hazard of each mileston by foreign
```{r results="asis",warning=FALSE,message=FALSE}

ts0 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==0), data=dat7)
ts0
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==1), data=dat7)
ts1

h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)

pointestf0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestf1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestf0) <- c("time","logith")
colnames(pointestf1) <- c("time","logith")
pointestf <- rbind(pointestf0, pointestf1)
pointestf$foreign <- c(rep(0,9),rep(1,9))
```
mean log hazard of each mileston by male
```{r}
ts0 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(male==0), data=dat7)
summary(ts0)
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(male==1), data=dat7)
ts1

ts0$lower


h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)

pointestm0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestm1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestm0) <- c("time","logith")
colnames(pointestm1) <- c("time","logith")
pointestm <- rbind(pointestm0, pointestm1)
pointestm$male <- c(rep(0,9),rep(1,9))
```
mean log hazard of each milestone by motivehigh
```{r}
ts0 <- survfit( Surv(ms, event)~ 1, conf.type="none", subset=(motivhigh==0), data=dat7)
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="none", subset=(motivhigh==1), data=dat7)

h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)
#logith0<-odds0
#logith1<-odds1

pointestmotiv0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestmotiv1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestmotiv0) <- c("time","logith")
colnames(pointestmotiv1) <- c("time","logith")
pointestmotiv <- rbind(pointestmotiv0, pointestmotiv1)
pointestmotiv$motivhigh <- c(rep(0,9),rep(1,9))
```
mean log hazard for each milestone by pretest score above or below median
```{r}
ts0 <- survfit( Surv(ms, event)~ 1, conf.type="none", subset=(testabovemedian==0), data=dat7)
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="none", subset=(testabovemedian==1), data=dat7)

h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)
#logith0<-odds0
#logith1<-odds1

pointestpretest0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestpretest1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestpretest0) <- c("time","logith")
colnames(pointestpretest1) <- c("time","logith")
pointestpretest <- rbind(pointestpretest0, pointestpretest1)
pointestpretest$abovemedian <- c(rep(0,9),rep(1,9))
```
```{r}
datC <- datK
save(pointestm, file='male_logith_dotplotdata.RData')
save(pointestf, file='foreign_logith_dotplotdata.RData')
save(pointestmotiv, file='motive_logith_dotplotdata.RData')
save(pointestpretest, file='pretest_logith_dotplotdata.RData')
save(datL, file = 'male_linear_plotdata.RData')
save(datC, file = 'male_quadratic_plotdata.RData')
save(datC, datL, pointestm,pointestf,pointestmotiv,pointestpretest ,file = 'male_foreign_cubic_linear_point_data.RData')
```

