---
title: "Survival Analysis"
output: html_notebook
---
```{r}
load(url("https://github.com/bossaround/MOOC_CS50/raw/master/CS50_MOOC_Survival_Analysis_Data_0.RData"))
load(url("https://github.com/bossaround/MOOC_CS50/raw/master/CS50_MOOC_Survival_Analysis_Data_1.RData"))
```
This is the model used to draw the hazard plot
```{r}
model.for.plot <- glm(drop ~ milestone + milestone2 + milestone3+ male +milestone*male +  age +  testtot  +foreign + gamehour5 + testtot*milestone  , family="binomial", data=dat7)
summary(model.for.plot)
```


```{r}
timevaryingmodel <- glm(drop ~ milestone + milestone2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*ms + testtot*milestone + male*milestone2  + age*milestone+  testtot*milestone2 + click +click*milestone +click*milestone2, data=dat7)
summary(timevaryingmodel)
```

```{r}
model1 <- glm(drop ~ milestones + milestones2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv, data=dat7)

model2 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2 , data=dat7)

model3 <- glm(drop ~ milestones + milestones2+ male + age +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv  + click , data=dat7)

model4 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2 + click, data=dat7)

model5 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2  + click +click*milestones +click*milestones2, data=dat7)
```
```{r results="asis",warning=FALSE,message=FALSE}
 stargazer :: stargazer(model1,model2, model3, model4 ,model5, type="html",
                        dep.var.labels = "Logit Hazard",
                       title = "Discrete survival analysis predicting logit hazard of dropout, including final assignment")
```
```{r}
dat10 <- dat7[dat7$milestones<9,]
table(dat7$milestones)
table(dat7$milestones)
```
```{r}
model1 <- glm(drop ~ milestones + milestones2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv, data=dat10)

model2 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2 , data=dat10)

model3 <- glm(drop ~ milestones + milestones2+ male + age +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv  + click , data=dat10)

model4 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2 + click, data=dat10)

model5 <- glm(drop ~ milestones + milestones2+ male + age  +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*milestones+ csexperience*milestones2 + testtot*milestones +male*milestones+ male*milestones2  + age*milestones+ age*milestones2+ testtot*milestones2  + click +click*milestones +click*milestones2, data=dat10)
```
```{r results="asis",warning=FALSE,message=FALSE}
 stargazer :: stargazer(model1,model2, model3, model4 ,model5, type="html",
                        dep.var.labels = "Logit Hazard",
                       title = "Discrete survival analysis predicting logit hazard of dropout, excluding final assignment")
```
```{r results="asis",warning=FALSE,message=FALSE}
xafit1<-glm(drop~foreign, family="binomial", data=dat7)
summary(xafit1)
t<-data.frame(xafit1$coefficients)
p0<-t[1,1]
p1<-p0+t[2,1]

ts0 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==0), data=dat7)
ts0
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==1), data=dat7)
ts1

h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)

pointestf0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestf1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestf0) <- c("time","logith")
colnames(pointestf1) <- c("time","logith")
pointestf <- rbind(pointestf0, pointestf1)
pointestf$foreign <- c(rep(0,9),rep(1,9))


ts0f <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==0), data=datK)
ts0f
ts1f <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(foreign==1), data=datK)
ts1f

h0f<-ts0f$n.event/ts0f$n.risk
h1f<-ts1f$n.event/ts1f$n.risk

odds0f<-h0f/(1-h0f)
odds1f<-h1f/(1-h1f)
logith0f<-log(odds0f)
logith1f<-log(odds1f)

pointestf0f <- data.frame(ts1f$time[1:9]+1, logith0f[1:9])
pointestf1f <- data.frame(ts1f$time[1:9]+1, logith1f[1:9])
colnames(pointestf0f) <- c("time","logith")
colnames(pointestf1f) <- c("time","logith")
pointestff <- rbind(pointestf0f, pointestf1f)
pointestff$foreign <- c(rep(0,9),rep(1,9))
#logith0<-odds0
#logith1<-odds1
dat7$ms2 <- dat7$ms^2
xafit8<-glm(event~foreign + ms +ms2, family="binomial", data=dat7)
summary(xafit8)

t<-data.frame(xafit8$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 

plot(ts0$time[1:8], logith0[1:8], type="p", ylab="Estimated Logit Hazard", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 9), col="blue")
par(new=T) 
plot(ts1$time[1:8], logith1[1:8], type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
legend(6,1, # places a legend at the appropriate place 
c('Location=US','Location=Foreign'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```
```{r}
dat4$motivhigh <- NA
dat4$motivhigh[which(dat4$motiv < 0.35)] <- 0
dat4$motivhigh[which(dat4$motiv > 0.35)] <- 1
table(dat4$motivhigh)

xbfit1<-glm(event~motiv, family="binomial", data=dat5)
summary(bfit1)
t<-data.frame(xbfit1$coefficients)
p0<-t[1,1] + t[2,1]*(-0.9)
p1<-t[1,1] + t[2,1]*0.9


tt0 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(motivhigh==0), data=dat4)
tt1 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(motivhigh==1), data=dat4)

th0<-tt0$n.event/tt0$n.risk
th1<-tt1$n.event/tt1$n.risk

todds0<-th0/(1-th0)
todds1<-th1/(1-th1)
tlogith0<-log(todds0)
tlogith1<-log(todds1)
#logith0<-odds0
#logith1<-odds1
tt0$time <- tt0$time[1:8]
tt1$time <- tt1$time[1:8]
tlogith0 <- tlogith0[1:8]
tlogith1 <- tlogith1[1:8]

xbfit2<-glm(event~motiv + ms + ms2, family="binomial", data=dat5)
summary(xbfit2)

t<-data.frame(xbfit2$coefficients)
y0<-t[1,1] + t[2,1]*(-1) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 
y1<-t[1,1] + t[2,1]*(1) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2

plot(tt0$time, tlogith0, type="p", ylab="", xlab="", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time[1:8], tlogith1[1:8], type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
legend(6.5,1, # places a legend at the appropriate place 
c('motiv= +1SD','motiv= -1SD'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```

```{r results="asis",warning=FALSE,message=FALSE}
dat7$keep <- 1- dat7$drop
afit1<-glm(drop~male, family="binomial", data=dat7)
summary(afit1)
t<-data.frame(afit1$coefficients)
p0<-t[1,1]
p1<-p0+t[2,1]
dat8<- dat3
 # ts0 <- survfit( Surv(ms, event)~ 1, conf.type="none", subset=(male==0), data=dat8)
ts0 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(male==0), data=dat7)
summary(ts0)
ts1 <- survfit( Surv(ms, event)~ 1, conf.type="log", subset=(male==1), data=dat7)
ts1

ts0$lower


h0<-ts0$n.event/ts0$n.risk
h1<-ts1$n.event/ts1$n.risk

odds0<-h0/(1-h0)
odds1<-h1/(1-h1)
logith0<-log(odds0)
logith1<-log(odds1)

pointestm0 <- data.frame(ts1$time[1:9]+1, logith0[1:9])
pointestm1 <- data.frame(ts1$time[1:9]+1, logith1[1:9])
colnames(pointestm0) <- c("time","logith")
colnames(pointestm1) <- c("time","logith")
pointestm <- rbind(pointestm0, pointestm1)
pointestm$male <- c(rep(0,9),rep(1,9))
#logith0<-odds0
#logith1<-odds1
plot(ts0$time[1:10], logith0[1:10], type="p", ylab="Estimated Logit", xlab="Grade", 
     ylim=c(-5, 2), xlim=c(1, 10), col="red")
par(new=T) 
plot(ts1$time[1:10], logith1[1:10], type="p", ylab=" ", ylim=c(-5, 2), xlim=c(1, 10), xlab="", col="blue")
abline(h=c(p1), lty=1, col="blue")
abline(h=c(p0), lty=1, col="red")
```


```{r results="asis",warning=FALSE,message=FALSE}
afit2<-glm(drop~male + milestones, family="binomial", data=dat9)
summary(afit2)

t<-data.frame(afit2$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:9]
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:9]

plot(ts0$time[1:9], logith0[1:9], type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 2), xlim=c(1, 10), col="red")
par(new=T) 
plot(ts1$time[1:9], logith1[1:9], type="p", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:9], y0, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="red")
par(new=T)
plot(ts1$time[1:9], y1, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
```


```{r results="asis",warning=FALSE,message=FALSE}
afit5<-glm(drop~male + milestones + male*milestones, family="binomial", data=dat9)
summary(afit5)

t<-data.frame(afit5$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:9]
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:9] + t[4,1]*ts0$time[1:9]

plot(ts0$time[1:9], logith0[1:9], type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 2), xlim=c(1, 10), col="red")
par(new=T) 
plot(ts1$time[1:9], logith1[1:9], type="p", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:9], y0, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="red")
par(new=T)
plot(ts1$time[1:9], y1, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
```
```{r results="asis",warning=FALSE,message=FALSE}
afit3<-glm(drop~male + factor(milestones), family="binomial", data=dat9)
summary(afit3)

t<-data.frame(cbind(y=afit3$linear.predictors, time=dat9$milestones, male=dat9$male))
t
t<- t[1:16,]
#t[18,]<-c(-16.61,9,1)
t0<-t[t$male==0,]
#t0<-t0[order(t0$time),]
t1<-t[t$male==1,]
#t1<-t1[order(t1$time),]

plot(ts0$time, logith0, type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 8), col="red")
par(new=T) 
plot(ts1$time, logith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="blue")
par(new=T)
plot(t0$time, t0$y, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="red")
par(new=T)
plot(t1$time, t1$y, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="blue")

```


```{r results="asis",warning=FALSE,message=FALSE}
afit4<-glm(event~male + factor(ms) + male*factor(ms), family="binomial", data=dat5)
summary(afit4)
t<-data.frame(cbind(y=afit4$linear.predictors, time=dat5$ms, male=dat5$male))
t<- t[1:16,]
t0<-t[t$male==0,]
#t0<-t0[order(t0$time),]
t1<-t[t$male==1,]
#t1<-t1[order(t1$time),]

plot(ts0$time, logith0, type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 8), col="red")
par(new=T) 
plot(ts1$time, logith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="blue")
par(new=T)
plot(t0$time, t0$y, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="red")
par(new=T)
plot(t1$time, t1$y, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 8), xlab="", col="blue")
```
```{r results="asis",warning=FALSE,message=FALSE}
dat9$milestones2 <- dat9$milestones^2
dat9$milestones3 <- dat9$milestones^3

afit6<-glm(drop~male + milestones +milestones2 +milestones3, family="binomial", data=dat9)
summary(afit6)

t<-data.frame(afit6$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:9] + t[4,1]*ts0$time[1:9]^2 + t[5,1]*ts0$time[1:9]^3
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:9] + t[4,1]*ts0$time[1:9]^2 + t[5,1]*ts0$time[1:9]^3

plot(ts0$time[1:9], logith0[1:9], type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 2), xlim=c(1, 10), col="red")
par(new=T) 
plot(ts1$time[1:9], logith1[1:9], type="p", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:9], y0, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="red")
par(new=T)
plot(ts1$time[1:9], y1, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
```
```{r results="asis",warning=FALSE,message=FALSE}

afit8<-glm(drop~male + milestones +milestones2+milestones*male+milestones2*male, family="binomial", data=dat9)
summary(afit8)

t<-data.frame(afit8$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:9] + t[4,1]*ts0$time[1:9]^2 
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:9] + t[4,1]*ts0$time[1:9]^2 + t[5,1]*ts0$time[1:9] + t[6,1]*ts0$time[1:9]^2 

plot(ts0$time[1:9], logith0[1:9], type="p", ylab="Estimated Logit Harzard", xlab="milestone", 
     ylim=c(-2, 2), xlim=c(1, 10), col="red")
par(new=T) 
plot(ts1$time[1:9], logith1[1:9], type="p", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:9], y0, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="red")
par(new=T)
plot(ts1$time[1:9], y1, type="l", ylab=" ", ylim=c(-2, 2), xlim=c(1, 10), xlab="", col="blue")
legend(6,2, # places a legend at the appropriate place 
c('gender=male','gender=female'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```
```{r results="asis",warning=FALSE,message=FALSE}
k02 <- matrix(c(0, 0, 2, 4, 0, 0), 1)
k12 <- matrix(c(0, 1, 2, 4, 2, 4), 1)
kd2 <- k12 - k02
t2 <- glht(afit8, linfct = kd2)
summary(t2)

k03 <- matrix(c(0, 0, 3, 9, 0, 0), 1)
k13 <- matrix(c(0, 1, 3, 9, 3, 9), 1)
kd3 <- k13 - k03
t3 <- glht(afit8, linfct = kd3)
summary(t3)

k04 <- matrix(c(0, 0, 4, 16, 0, 0), 1)
k14 <- matrix(c(0, 1, 4, 16, 4, 16), 1)
kd4 <- k14 - k04
t4 <- glht(afit8, linfct = kd4)
summary(t4)

k05 <- matrix(c(0, 0, 5, 25, 0, 0), 1)
k15 <- matrix(c(0, 1, 5, 25, 5, 25), 1)
kd5 <- k15 - k05
t5 <- glht(afit8, linfct = kd5)
summary(t5)

k06 <- matrix(c(0, 0, 6, 36, 0, 0), 1)
k16 <- matrix(c(0, 1, 6, 36, 6, 36), 1)
kd6 <- k16 - k06
t6 <- glht(afit8, linfct = kd6)
summary(t6)
```
```{r results="asis",warning=FALSE,message=FALSE}

afit9<-glm(event~male + ms +ms2+ms*male, family="binomial", data=dat5)
summary(afit9)

t<-data.frame(afit9$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]

plot(ts0$time[1:8], logith0[1:8], type="p", ylab="Estimated Logit of Harzard", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(ts1$time[1:8], logith1[1:8], type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
legend(6,1, # places a legend at the appropriate place 
c('gender=male','gender=female'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```
```{r results="asis",warning=FALSE,message=FALSE}
k02 <- matrix(c(0, 0, 2, 4, 0), 1)
k12 <- matrix(c(0, 1, 2, 4, 2), 1)
kd2 <- k12 - k02
t2 <- glht(afit9, linfct = kd2)
summary(t2)

k03 <- matrix(c(0, 0, 3, 9, 0), 1)
k13 <- matrix(c(0, 1, 3, 9, 3), 1)
kd3 <- k13 - k03
t3 <- glht(afit9, linfct = kd3)
summary(t3)

k04 <- matrix(c(0, 0, 4, 16, 0), 1)
k14 <- matrix(c(0, 1, 4, 16, 4), 1)
kd4 <- k14 - k04
t4 <- glht(afit9, linfct = kd4)
summary(t4)

k05 <- matrix(c(0, 0, 5, 25, 0), 1)
k15 <- matrix(c(0, 1, 5, 25, 5), 1)
kd5 <- k15 - k05
t5 <- glht(afit9, linfct = kd5)
summary(t5)

k06 <- matrix(c(0, 0, 6, 36, 0), 1)
k16 <- matrix(c(0, 1, 6, 36, 6), 1)
kd6 <- k16 - k06
t6 <- glht(afit9, linfct = kd6)
summary(t6)
```
```{r results="asis",warning=FALSE,message=FALSE}

afit8<-glm(event~male + ms +ms2, family="binomial", data=dat5)
summary(afit8)

t<-data.frame(afit8$coefficients)
y0<-t[1,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 
y1<-t[1,1] + t[2,1] + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 

plot(ts0$time[1:8], logith0[1:8], type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-4, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(ts1$time[1:8], logith1[1:8], type="p", ylab=" ", ylim=c(-4, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-4, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-4, 1), xlim=c(1, 9), xlab="", col="blue")
```
```{r}
dat4$testhigh <- NA
dat4$testhigh[which(dat4$testtot < -1.4 & dat4$testtot > -2)] <- 0
dat4$testhigh[which(dat4$testtot < 0 & dat4$testtot > -0.03)] <- 1
table(dat4$testhigh)
```
```{r}
dat4$testabovemedian <- NA
dat4$testabovemedian[which(dat4$testtot < 0)] <- 0
dat4$testabovemedian[which(dat4$testtot > 0)] <- 1
table(dat4$testabovemedian)
```

```{r results="asis",warning=FALSE,message=FALSE}

bfit1<-glm(event~testtot, family="binomial", data=dat5)
summary(bfit1)
t<-data.frame(bfit1$coefficients)
p0<-t[1,1] + t[2,1]*(-0.6)
p1<-t[1,1] + t[2,1]*0.7


tt0 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(testabovemedian==0), data=dat4)
tt1 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(testabovemedian==1), data=dat4)

th0<-tt0$n.event/tt0$n.risk
th1<-tt1$n.event/tt1$n.risk

todds0<-th0/(1-th0)
todds1<-th1/(1-th1)
tlogith0<-log(todds0)
tlogith1<-log(todds1)
#logith0<-odds0
#logith1<-odds1
tt0$time <- tt0$time[1:8]
tt1$time <- tt1$time[1:8]
tlogith0 <- tlogith0[1:8]
tlogith1 <- tlogith1[1:8]
tlogith0[6] = -1.42
plot(tt0$time, tlogith0, type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time, tlogith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
abline(h=c(p1), lty=1, col="blue")
abline(h=c(p0), lty=1, col="red")
```
```{r results="asis",warning=FALSE,message=FALSE}
bfit1<-glm(event~testtot, family="binomial", data=dat5)
summary(bfit1)
t<-data.frame(bfit1$coefficients)
p0<-t[1,1] + t[2,1]*(-0.6)
p1<-t[1,1] + t[2,1]*0.7


tt0 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(testabovemedian==0), data=dat4)
tt1 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(testabovemedian==1), data=dat4)

th0<-tt0$n.event/tt0$n.risk
th1<-tt1$n.event/tt1$n.risk

todds0<-th0/(1-th0)
todds1<-th1/(1-th1)
tlogith0<-log(todds0)
tlogith1<-log(todds1)
#logith0<-odds0
#logith1<-odds1
tt0$time <- tt0$time[1:8]
tt1$time <- tt1$time[1:8]
tlogith0 <- tlogith0[1:8]
tlogith1 <- tlogith1[1:8]

bfit1<-glm(event~testtot + ms + ms2 + ms*testtot + ms2*testtot , family="binomial", data=dat5)
summary(bfit1)

t<-data.frame(bfit1$coefficients)
y0<-t[1,1] + t[2,1]*(-.7) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(-.7) + t[6,1]*(-.7)*ts0$time[1:8]^2  
y1<-t[1,1] + t[2,1]*(1) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(1) + t[6,1]*(1)*ts0$time[1:8]^2  

plot(tt0$time, tlogith0, type="p", ylab="", xlab="", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time[1:8], tlogith1[1:8], type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
legend(5.5,1, # places a legend at the appropriate place 
c('CS-Readiness= 10/11','CS-Readiness=7/11'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```
```{r results="asis",warning=FALSE,message=FALSE}
k02 <- matrix(c(0, 0, 2, 4, 0), 1)
k12 <- matrix(c(0, 1, 2, 4, 2), 1)
kd2 <- k12 - k02
t2 <- glht(bfit1, linfct = kd2)
summary(t2)

k03 <- matrix(c(0, 0, 3, 9, 0), 1)
k13 <- matrix(c(0, 1, 3, 9, 3), 1)
kd3 <- k13 - k03
t3 <- glht(bfit1, linfct = kd3)
summary(t3)

k04 <- matrix(c(0, 0, 4, 16, 0), 1)
k14 <- matrix(c(0, 1, 4, 16, 4), 1)
kd4 <- k14 - k04
t4 <- glht(bfit1, linfct = kd4)
summary(t4)

k05 <- matrix(c(0, 0, 5, 25, 0), 1)
k15 <- matrix(c(0, 1, 5, 25, 5), 1)
kd5 <- k15 - k05
t5 <- glht(bfit1, linfct = kd5)
summary(t5)

k06 <- matrix(c(0, 0, 6, 36, 0), 1)
k16 <- matrix(c(0, 1, 6, 36, 6), 1)
kd6 <- k16 - k06
t6 <- glht(bfit1, linfct = kd6)
summary(t6)
```
```{r}
dat4$csexpabovemedian <- NA
dat4$csexpabovemedian[which(dat4$csexperience <= -0.15)] <- 0
dat4$csexpabovemedian[which(dat4$csexperience > -0.15)] <- 1
table(dat4$csexpabovemedian)
```
```{r results="asis",warning=FALSE,message=FALSE}

cfit1<-glm(event~csexperience, family="binomial", data=dat5)
summary(bfit1)
t<-data.frame(cfit1$coefficients)
p0<-t[1,1] + t[2,1]*(-1.03)
p1<-t[1,1] + t[2,1]*1.03


tt0 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(csexpabovemedian==0), data=dat4)
tt1 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(csexpabovemedian==1), data=dat4)

th0<-tt0$n.event/tt0$n.risk
th1<-tt1$n.event/tt1$n.risk

todds0<-th0/(1-th0)
todds1<-th1/(1-th1)
tlogith0<-log(todds0)
tlogith1<-log(todds1)
#logith0<-odds0
#logith1<-odds1
tt0$time <- tt0$time[1:8]
tt1$time <- tt1$time[1:8]
tlogith0 <- tlogith0[1:8]
tlogith1 <- tlogith1[1:8]

plot(tt0$time, tlogith0, type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time, tlogith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
abline(h=c(p1), lty=1, col="blue")
abline(h=c(p0), lty=1, col="red")
```
```{r results="asis",warning=FALSE,message=FALSE}

cfit1<-glm(event~csexperience + ms + ms2 + ms*csexperience, family="binomial", data=dat5)
summary(cfit1)

t<-data.frame(cfit1$coefficients)
y0<-t[1,1] + t[2,1]*(-.738) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(-.738) 
y1<-t[1,1] + t[2,1]*(.836) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(.836)   

plot(tt0$time, tlogith0, type="p", ylab="", xlab="", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time, tlogith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
legend(5.5,1, # places a legend at the appropriate place 
c('experience=mean+1sd','experience=mean-1sd'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```
```{r}
dat4$ageabovemedian <- NA
dat4$ageabovemedian[which(dat4$age<= -0.185)] <- 0
dat4$ageabovemedian[which(dat4$age > -0.185)] <- 1
table(dat4$ageabovemedian)
```
```{r results="asis",warning=FALSE,message=FALSE}

dfit1<-glm(event~age, family="binomial", data=dat5)
summary(dfit1)
t<-data.frame(dfit1$coefficients)
p0<-t[1,1] + t[2,1]*(-.995)
p1<-t[1,1] + t[2,1]*.995


tt0 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(ageabovemedian==0), data=dat4)
tt1 <- survfit( Surv(ms, 1-censor)~ 1, conf.type="none", subset=(ageabovemedian==1), data=dat4)

th0<-tt0$n.event/tt0$n.risk
th1<-tt1$n.event/tt1$n.risk

todds0<-th0/(1-th0)
todds1<-th1/(1-th1)
tlogith0<-log(todds0)
tlogith1<-log(todds1)
#logith0<-odds0
#logith1<-odds1
tt0$time <- tt0$time[1:8]
tt1$time <- tt1$time[1:8]
tlogith0 <- tlogith0[1:8]
tlogith1 <- tlogith1[1:8]

plot(tt0$time, tlogith0, type="p", ylab="Estimated Logit", xlab="milestone", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time, tlogith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
abline(h=c(p1), lty=1, col="blue")
abline(h=c(p0), lty=1, col="red")
```
```{r results="asis",warning=FALSE,message=FALSE}

cfit1<-glm(event~age + ms + ms2 + ms*age + ms2*age, family="binomial", data=dat5)
summary(cfit1)

t<-data.frame(cfit1$coefficients)
y0<-t[1,1] + t[2,1]*(-.995) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(-.995) +  t[6,1]*(-.995)*ts0$time[1:8]^2
y1<-t[1,1] + t[2,1]*(.995) + t[3,1]*ts0$time[1:8] + t[4,1]*ts0$time[1:8]^2 + t[5,1]*ts0$time[1:8]*(.995) +  t[6,1]*(.995)*ts0$time[1:8]^2  

plot(tt0$time, tlogith0, type="p", ylab="", xlab="", 
     ylim=c(-2, 1), xlim=c(1, 9), col="red")
par(new=T) 
plot(tt1$time, tlogith1, type="p", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
par(new=T)
plot(ts1$time[1:8], y0, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="red")
par(new=T)
plot(ts1$time[1:8], y1, type="l", ylab=" ", ylim=c(-2, 1), xlim=c(1, 9), xlab="", col="blue")
legend(7,1, # places a legend at the appropriate place 
c('age=36','age=20'), # puts text in the legend 
lty=c(1,1), # gives the legend appropriate symbols (lines)
lwd=c(2.5,2.5),col=c('blue','red')) # gives the legend lines the correct color and width
```

```{r results="asis",warning=FALSE,message=FALSE}
modelA<-glm(event~factor(ms), family="binomial", data=dat5)
modelB<-glm(event~male + factor(ms), family="binomial", data=dat5)
modelC<-glm(event~male + factor(ms) + male*factor(ms), family="binomial", data=dat5)
modelD<-glm(event~male + ms, family="binomial", data=dat5)
modelE<-glm(event~male + ms + male*ms, family="binomial", data=dat5)
modelF<-glm(event~male + ms + ms2 + ms3, family="binomial", data=dat5)
```
```{r results="asis",warning=FALSE,message=FALSE}
 stargazer :: stargazer(modelA,modelB,modelC,modelD,modelE,  type="html")
```
```{r results="asis",warning=FALSE,message=FALSE}
anova(modelB,modelC, test = "Chisq")
anova(modelB,modelD, test = "Chisq")
anova(modelD,modelE, test = "Chisq")
anova(modelB,modelE, test = "Chisq")
anova(modelB,modelF, test = "Chisq")


```

```{r results="asis",warning=FALSE,message=FALSE}
modelX<-glm(event~male + factor(ms) + age +edu + factor(enrollment_mode) + reason + cert+oc_reg + oc_comp + fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ nohelp+ gamehour5+maxproglang+totalproglang, family="binomial", data=dat5)

modelY<-glm(event~male + factor(ms) + age +edu + factor(enrollment_mode) +oc_reg+ fam + engfluent + nointendcomplete  + testtot  +enrolltime +foreign + extrovert+  gamehour5+maxproglang+totalproglang, family="binomial", data=dat5)

modelF<-glm(event~male + factor(ms) + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang, family="binomial", data=dat5)

modelG<-glm(event~male + ms, family="binomial", data=dat5)
modelG2<-glm(event~male + ms + male*ms, family="binomial", data=dat5)

modelH<-glm(event~male +ms + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang, family="binomial", data=dat5)

modelH2<-glm(event~male +ms + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang + testtot*ms, family="binomial", data=dat5)

modelH3<-glm(event~male +ms + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang + foreign*ms, family="binomial", data=dat5)

modelH4<-glm(event~male +ms + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang + maxproglang*ms, family="binomial", data=dat5)

modelH5<-glm(event~male +ms + age +edu +factor(enrollment_mode) +oc_comp+ fam + engfluent + nointendcomplete  + factor(school) +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5+maxproglang+totalproglang + maxproglang*ms + testtot*ms, family="binomial", data=dat5)
```
```{r results="asis",warning=FALSE, message=FALSE}
modelI<-glm(event~ms+ms2+male + age +edu  + engfluent  + school +  numlang + testtot  +enrolltime +foreign + extrovert+ gamehour5 + csexperience + motiv , family="binomial", data=dat5)

modelI1<-glm(event~male +ms +ms2+ age +edu  +  school + testtot  +enrolltime +foreign + extrovert+ gamehour5 + csexperience + motiv, family="binomial", data=dat5)

modelI2<-glm(event~male +ms +ms2+ age +edu +  school +  testtot +foreign + extrovert+ gamehour5 + csexperience + motiv, family="binomial", data=dat5)


modelI3<-glm(event~ms +ms2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*ms + testtot*ms + male*ms + age*ms , family="binomial", data=dat5)
modelI4<-glm(event~ms + male + age +edu +school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*ms + testtot*ms + male*ms +age*ms , family="binomial", data=dat5)

modelI5<-glm(event~ms +ms2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*ms + testtot*ms + male*ms + age*ms+csexperience*ms2 + testtot*ms2 + male*ms2 +age*ms2 , family="binomial", data=dat5)
modelI6<-glm(event~ms +ms2+ male + age +edu +  school +  testtot  +foreign + extrovert+ gamehour5 + csexperience + motiv +csexperience*ms + testtot*ms + male*ms  + age*ms+  testtot*ms2 , family="binomial", data=dat5)
```
```{r results="asis",warning=FALSE,message=FALSE}
 stargazer :: stargazer(modelA,modelB,modelX, modelY, modelF, modelG,modelG2, modelH,modelH2,modelH3,modelH4,modelH5,modelI,modelI1 , type="html")
```
```{r results="asis",warning=FALSE,message=FALSE}
 stargazer :: stargazer(modelI,modelI2, modelI3, modelI4 ,modelI6, type="html",
                        dep.var.labels = "Logit Hazard",
                       title = "Discrete survival analysis predicting logit hazard of dropout")
```