---
title: "Survival Analysis Models"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---
Three models are included thus far. 

A quatrics model(p1 - Final)

A discrete model (p1-p7 as linear, and p8.optional & Final as dummies)

A regional model (p1-p7, whereas p8 & Final are excluded)

Each of the models contains a base model and a final model.

The base model only includes milestones.

The final model includes all significant predictors and interaction terms.

```{r include=FALSE}
library(rmarkdown)
library(stargazer)
library(ggplot2)
#load(url("https://raw.github.com/bossaround/MOOC_CS50/master/CS50_MOOC_Survival_Analysis_Data_0.RData"))
#use dat9 from Data_1, or Data_2 the time var is milestones, make sure it is plural.
load(url("https://raw.github.com/bossaround/MOOC_CS50/master/CS50_MOOC_Survival_Analysis_Data_2.RData"))
# load(url("https://raw.github.com/bossaround/MOOC_CS50/master/csexperience_logith_dotplotdata.RData"))
# load(url("https://raw.github.com/bossaround/MOOC_CS50/master/male_logith_dotplotdata.RData"))
# load(url("https://raw.github.com/bossaround/MOOC_CS50/master/pretest_logith_dotplotdata.RData"))
# load(url("https://raw.github.com/bossaround/MOOC_CS50/master/foreign_logith_dotplotdata.RData"))
# load(url("https://raw.github.com/bossaround/MOOC_CS50/master/age_logith_dotplotdata.RData"))

```
```{r include=FALSE}
# dat7$csexperience <- as.numeric(dat7$csexperience)
# dat7$motiv <- as.numeric(dat7$motiv)
dat9$csexperience <- as.numeric(dat9$csexperience)
dat9$motiv <- as.numeric(dat9$motiv)
dat8 <- dat9
dat8$m8 <- 0
dat8$mf <- 0
dat8$m8[which(dat8$milestones==8)] <- 1
dat8$mf[which(dat8$milestones==9)] <- 1
```
```{r include=FALSE}
dat8$milestones[which(dat8$milestones==8)] <- 0
dat8$milestones[which(dat8$milestones==9)] <- 0

```
```{r include=FALSE}
# This is the model used to draw the hazard plot with an 
# interaction effect with male
model.for.plot1 <- glm(drop ~ milestones + milestones2 + milestones3+ male +milestones*male +  age.scale.correct +  testtot  +foreign + gamehour5 + testtot*milestones  , family="binomial", data=dat9)

summary(model.for.plot1)
```
```{r include=FALSE}
m.quatrics.base <- glm(drop ~ milestones + milestones2 , family="binomial", data=dat9)
summary(m.quatrics.base)
```

```{r include=FALSE}
m.discrete.base <- glm(drop ~ milestones + m8 + mf, family = "binomial", data = dat8)
summary(m.discrete.base)
```
```{r include=FALSE}
dat10 <- dat9[dat9$milestones <8,]
```

```{r include=FALSE}
m.quatrics.full <- glm(drop ~ milestones +milestones2+csexperience+male+school +testtot +age.scale.raw+motiv+gamehour5+foreign+ milestones*testtot+milestones*csexperience +milestones*male +milestones*age.scale.raw , family = "binomial", data=dat9)
summary(m.quatrics.full)
```

```{r include=FALSE}
m.discrete.full <- glm(drop ~ milestones +m8 + mf +csexperience+male +testtot +age.scale.raw+school+motiv+gamehour5+foreign+ milestones*testtot+ m8*testtot + mf*testtot+milestones*csexperience  + m8*csexperience + mf*csexperience + milestones*male + m8*male + mf*male + milestones*age.scale.raw + m8*age.scale.raw + mf*age.scale.raw , family = "binomial", data=dat8)
summary(m.discrete.full)
```
```{r include=FALSE}
m.regional.base <- glm(drop ~ milestones , family = "binomial", data=dat10)
summary(m.regional.base)
```
```{r include=FALSE}
m.regional.full <- glm(drop ~ milestones +csexperience+male +testtot +age.scale.raw+motiv+gamehour5+foreign+ milestones*testtot+milestones*csexperience +milestones*male + milestones*age.scale.raw, family = "binomial", data=dat9)
summary(m.regional.full)
```


```{r results="asis",warning=FALSE,message=FALSE, echo=FALSE}
 stargazer :: stargazer(m.quatrics.base,m.quatrics.full,m.regional.base,m.regional.full ,m.discrete.base,m.discrete.full, type="html",
                        dep.var.labels = "Logit Odd",
                       title = "Survival analysis predicting logit hazard of dropout",
                       model.names = FALSE,
                       column.labels = c("quatrics-base&nbsp;&nbsp;","quatrics-final&nbsp;&nbsp;&nbsp;&nbsp;","regional-base&nbsp;&nbsp;&nbsp;&nbsp;","regional-final&nbsp;&nbsp;&nbsp;&nbsp;","discrete-base&nbsp;&nbsp;&nbsp;&nbsp;","discrete- final&nbsp;&nbsp;&nbsp;&nbsp;") )
```